FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir \
    pandas \
    numpy \
    scikit-learn \
    joblib \
    lightgbm

WORKDIR /opt/ml/processing/code